name: pathpilot
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cuda-toolkit
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
    - numpy>=1.21.0
    - opencv-python>=4.5.0
    - transformers>=4.30.0
    - accelerate>=0.20.0
    - bitsandbytes>=0.41.0
    - safetensors>=0.3.1
    - segment-anything>=1.0
    - mast3r-slam @ git+https://github.com/paulburkhardt/MASt3R-SLAM.git
    - pyyaml>=6.0
    - tqdm>=4.65.0
    - pillow>=9.0.0
    - einops>=0.6.1 