pipeline:
  components:
    # Load video data for SLAM processing
    - type: MAST3RSLAMVideoDataset
      config:
        video_path: Data/Videos/back_and_forth.mp4
        mast3r_slam_config_path: "configs/MASt3R-SLAM_configs/no_calib.yaml"
        
    # Run MAST3R SLAM to generate point cloud and trajectory incrementally
    - type: MAST3RSLAMComponent
      config:
        point_cloud_method: accumulating
        c_confidence_threshold: 1.5 
        mast3r_slam_config_path: "configs/MASt3R-SLAM_configs/no_calib.yaml"
        segment_point_cloud: False
    
    # Incremental floor detection - waits for 3 frames, refines frequently for better accuracy
    - type: IncrementalFloorDetectionComponent
      config:
        min_frames: 3  # Wait for 3 frames before starting
        sample_ratio: 0.15  # Slightly more points for better accuracy
        ransac_threshold: 0.05
        min_inliers: 1000
        floor_threshold: 0.05
        refine_interval: 10  # Refine every 10 frames for better accuracy
        max_refinement_poses: 30  # Use last 30 poses for refinement
    
    # Find closest points incrementally - waits for floor detection
    - type: IncrementalClosestPointFinderComponent
      config:
        use_view_cone: true  # Set to true to enable view cone filtering
        cone_angle_deg: 45.0
        n_closest_points: 20  # Number of closest points to return
        use_segmentation_filter: False

        
    # Enhanced output writer with intermediate saving enabled
    - type: EnhancedSLAMOutputWriter
      config:
        output_dir: "enhanced_slam_outputs"
        output_name: "incremental_analysis_detailed"
        save_point_cloud: true
        save_trajectory: true
        save_floor_data: true
        save_closest_points: true
        save_yolo_detections: false  # Save YOLO detection results
        save_intermediate: true  # Save intermediate results
        intermediate_interval: 10   # Save intermediate results every 5 frames
        create_timestamped_dir: true
        analysis_format: "csv"  # Can be "json" or "csv" 
        save_closest_points_segment_ids: false  # Save segment IDs for closest points 
